### ISSUE TITLE
A few Suggestions

### ISSUE THREAD

**Issue by emhl** [RazerMoon/uploadToCloud#1]
This Plugin is pretty neat :D i got a few suggestions, which could make it even better imo.

- togglable option: if you exceed discords file size limit, automatically upload it to a file sharing service.
- adding the "upload to cloud" option to the + menu 
- Option to use a different file sharing service than ufile (one that supports direct links to a file (e.g. teknik.io) would be nice)

**Comment by RazerMoon** [comment]
I'm not sure about using teknik; they don't seem to support chunking, which may be problematic since I haven't implemented a progress indicator yet.

**Comment by RazerMoon** [comment]
Hmm, looks like there is some issue with the API.

![image](https://user-images.githubusercontent.com/33849459/127168315-5d8bef6c-f3f4-4935-883a-71249bbd5aa3.png)

![image](https://user-images.githubusercontent.com/33849459/127168691-c739be44-0c2c-4a7c-8029-6018a5852a48.png)

`Access-Control-Allow-Origin` should be set to `"*"`, and I'm pretty sure that is the correct URL https://help.teknik.io/API/v1/Upload

¯\_(ツ)_/¯

**Comment by emhl** [comment]
Sadly i got no experience using this API myself, but this is how it was implemented in ShareX :) https://github.com/ShareX/ShareX/blob/master/ShareX.UploadersLib/FileUploaders/Teknik.cs

**Comment by RazerMoon** [comment]
Sorry, but seems like Teknik won't be possible since Access-Control-Allow-Origin needs to be set to "*" for Discord.
