### ISSUE TITLE
Seems to no longer work?

### ISSUE THREAD

**Issue by SheepCommander** [RazerMoon/uploadToCloud#5]
![image](https://user-images.githubusercontent.com/66646514/148758181-93827a78-ae3e-423d-88c6-9a6b082897db.png)
![image](https://user-images.githubusercontent.com/66646514/148758315-db308c4d-eeb0-441e-a6c3-fd90b7e223d5.png)

**Comment by RazerMoon** [comment]
Can confirm still works as intended, jus use the plus button like in the demo gif.

![image](https://user-images.githubusercontent.com/33849459/148763713-696899c2-c9c1-4e42-bff2-b2dac3abf77d.png)

**Comment by SheepCommander** [comment]
Ohhh I didn't realize
